export const ROUTES = {
  HOME: '/root',
  ARTISTS: '/artists',
  GOODS: '/goods',
  MAP: '/map',
  BOOTHS: '/booths',
  TIMELINE: '/timeline',
  NOTICE: '/notice',
  NOTICE_POST: '/notice/post',
  MYPAGE: '/my-page',
  LOGIN: '/login',
  REGISTER: '/register',
  FIND_PASSWORD: '/password',
  CHANGE_PASSWORD: '/my-page/password',
  NOTICE_EDIT: '/notice/edit/:id',
  LOST_ITEM: '/lost-item',
};
