export const ROUTES = {
  HOME: '/',
  ARTISTS: '/artists',
  GOODS: '/goods',
  MAP: '/map',
  BOOTHS: '/booths',
  BOOTHS_DETAIL: '/booths/:id',
  TIMELINE: '/timeline',
  NOTICE: '/notice',
  NOTICE_POST: '/notice/post',
  MYPAGE: '/my-page',
  LOGIN: '/login',
  REGISTER: '/register',
  FIND_PASSWORD: '/password',
  CHANGE_PASSWORD: '/my-page/password',
  NOTICE_EDIT: '/notice/edit/:id',
  LOST_ITEM: '/lost-item',
  LOST_ITEM_CREATE: '/lost-item/create',
  LOST_ITEM_EDIT: '/lost-item/edit/:id',
  EVENTS: '/events',
  MYPAGE_ACCOUNT: '/my-page/account',
  MYPAGE_TIMELINE: '/my-page/timeline',
  MYPAGE_BOOTH: '/my-page/booth',
  MYPAGE_ADMIN: '/my-page/admin',
  NOT_FOUND: '*',
  CREATORS: '/creators',
};
